server:
  port: 8000
  servlet:
    context-path: /api/v1

spring:
  application:
    name: fitai-backend
  main:
    banner-mode: off

# OpenAPI / Swagger Config
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha

logging:
  level:
    root: INFO
    com.fitai.backend: DEBUG
